### ISSUE TITLE
[jdown] Joomla 4.1.4 release time incorrect. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1770]
Once again... details matter... history matters... seems once again lessons are not being learnt from previous reports! 

see: https://github.com/joomla/joomla-websites/issues/1749#issuecomment-1082204019

<img width="457" alt="Screen Shot 2022-05-24 at 18 33 04" src="https://user-images.githubusercontent.com/400092/170097287-7fa10773-fd22-47db-81a3-1621e773499b.png">

**Comment by HLeithner** [comment]
This is fixed already, thanks

**Comment by PhilETaylor** [comment]
It certainly was not fixed when I checked previously. And has a process been devised so that this is the last time this happens? Or has someone just gone into the database and manually changed it again? It is time that Joomla! started following processes and checklists rather than repeatedly making the same mistakes over and over again! There is a reason pilots and surgeons use checklists!

**Comment by PhilETaylor** [comment]
Happened again... for the third time https://github.com/joomla/joomla-websites/issues/1783
