### ISSUE TITLE
[jvols] Cannot save a Volunteer Group Report

### ISSUE THREAD

**Issue by artisanwebandprint** [joomla/joomla-websites#213]
Cannot save a Volunteer Group Report, get a 403 error that is Litespeed branded.

**Comment by mbabker** [comment]
Can you paste in the HTML snippet you're trying to publish?  mod_security rules have caused issues with that in the past.

**Comment by artisanwebandprint** [comment]
<p>Today four members of the JRD met to discuss major upgrades to the website which are long overdue including:</p>
<p>
1. Geo Radius - tool by which providers are located and found (update and deploy - remove resource consuming map from homepage of site)
2. Remove JRD archive - a 1.5 site.
3. Update the template to the Joomla approved version.
3. Translations to Portuguese (update and deploy).</p>
<p>We have scheduled a working group session for February 6th, Saturday from 11am - 2pm to implement these lingering changes. Please expect that the site will be down during this period for the update. Please email me directly with any questions or concerns.</p>

**Comment by mbabker** [comment]
None of that alone looks like an issue unless your IP raised a flag on the server.  But it's definitely an issue to take up direct with hosting, generally it's not something that I've seen addressed at the component's level.

**Comment by artisanwebandprint** [comment]
So you are suggesting I open a support ticket with Rochen over this?

**Comment by artisanwebandprint** [comment]
I am still having issues, so I created a ticket with Rochen:
https://my.rochen.com/portal/index.php?m=tickets&c=index&action=view&tid=174002

**Comment by MATsxm** [comment]
@artisanwebandprint any news?
Thanks

**Comment by artisanwebandprint** [comment]
Yes, Rochen fixed this, you can close it out.

Thanks,

Dawn

*Dawn Russell *
studio@artisanwebandprint.com
(802) 579-1340

<http://artisanwebandprint.com>

* [image: on Google+] <https://plus.google.com/+DawnRussell>
<http://www.linkedin.com/pub/dawn-russell/3b/a3a/673>*

**Comment by MATsxm** [comment]
Thanks
Closing it.
