### ISSUE TITLE
poor en-gb [jdev] 

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#457]
Help to make sure that all needed information are available for the community - should be 'is available'.

Test releases of the CMS before there are published - 'they are' not 'there'

We are asking for devs to join a release team- we should be showing them by good practice.

https://developer.joomla.org/news/656-call-for-volunteers-joomla-cms-release-team.html

**Comment by Sandra97** [comment]
I'm French so I might be wrong. As well as for "Role Informations", shouldn't it be "Role Information"?

**Comment by jeckodevelopment** [comment]
Thank you both for report.
Fixed!

Closing, re-open if needed.

**Comment by Hils** [comment]
I think you missed "Help to make sure that all needed information are available for the community" - it should be information....is - not are.
Thanks for fixing this @jeckodevelopment

**Comment by jeckodevelopment** [comment]
done, thank you!
