### ISSUE TITLE
[jevnt] 404 on footer login link

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#478]
`https://events.joomla.org/login` gives a 404 error.

**Comment by mbabker** [comment]
If he were using the current version of the template that's built by `JRoute` instead of being hardcoded as it once was...

**Comment by jeckodevelopment** [comment]
I guess that they use an outdated version of the template

**Comment by mbabker** [comment]
![brilliant-deduction](https://cloud.githubusercontent.com/assets/368545/17944896/32f9aa02-6a07-11e6-9030-0dab6d2bf8e5.jpg)

**Comment by jeckodevelopment** [comment]
ha!

**Comment by carcam** [comment]
This is already fixed in the site.

**Comment by zero-24** [comment]
You need to fix the error layout too. In that footer the link is wrong too.

**Comment by zero-24** [comment]
goto https://events.joomla.org/404 -> a 404 page to test --> see the footer link.

**Comment by carcam** [comment]
You are right!! Fixed now.

**Comment by Radek-Suski** [comment]
Thanks @carcam for taking care of it

**Comment by jeckodevelopment** [comment]
In home page of events.joomla.org i still have the link that goes to https://events.joomla.org/login (still 404)

**Comment by carcam** [comment]
That is probably your Browser cache. Try accessing with an "incognito" or "private browsing" window and the content will be updated.

**Comment by jeckodevelopment** [comment]
it works now. Thank you.
Please look at #479
