### ISSUE TITLE
[forum.joomla.org] Breadcrumbs

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#907]
As you can see the breadcrumbs are being truncated which makes them useless

I am not much of a css expert but it looks like its related to the breadcrumbs class

<img width="562" alt="screenshotr23-31-34" src="https://cloud.githubusercontent.com/assets/1296369/24380927/a2dc09fe-1345-11e7-995b-69fad0bcb31a.png">

**Comment by Joomv** [comment]
Hi Brian, can you take a look now, this appears to have been fixed, I've navigated to the same path as shown in your screenshot and I am not seeing truncation.
Thanks

**Comment by Joomv** [comment]
Closing this, if you still see it, please re-open

**Comment by brianteeman** [comment]
It is still happening for me in Chrome on Windows 10 but maybe its a browser extension

**Comment by brianteeman** [comment]
Re-opening as it is a confirmed issue in common.css at very high resolutions

```
.breadcrumbs .crumb a {
	display: inline-block;
	white-space: nowrap;
	text-overflow: ellipsis; 
	vertical-align: bottom;
	overflow: hidden; 
}


```

**Comment by Joomv** [comment]
I can confirm this happens, to replicate zoom in on Chrome to 150% or above and you will see the truncation.

The css above is only part of it, as it is also manipulated by JavaScript in these classes which are just below.

.breadcrumbs .crumb.wrapped-max a { max-width: 120px; }
.breadcrumbs .crumb.wrapped-wide a { max-width: 100px; }
.breadcrumbs .crumb.wrapped-medium a { max-width: 80px; }
.breadcrumbs .crumb.wrapped-small a { max-width: 60px; }
.breadcrumbs .crumb.wrapped-tiny a { max-width: 40px; }

It appears that when you go over the maximum width for wide, the JS flips the class to tiny.

The Css is in styles/joomla/theme/common.css and starts from line 614.

**Comment by ooffick** [comment]
I have changed this now, so that it is no longer truncated.

**Comment by Joomv** [comment]
Thank you, can confirm that this is now fixed!
Another mystery solved!

**Comment by brianteeman** [comment]
Thanks - its all cool now
